<?php $this->headTitle('Newsletter'); ?>

<div class="container">
  <h2>Abba and Kings</h2>
  <p>To stay up to date, kindly subscribe to our newsletter:</p>
  <form action="/action_page.php" class="was-validated">
    <div class="form-group">
      <label for="email"><b>Email:<b></label>
      <input type="email" class="form-control" id="email" placeholder="Enter your email" name="email" required>
      <div class="valid-feedback">Valid.</div>
      <div class="invalid-feedback">Please fill out this field.</div>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>