<?php

/**
 * This file generated by Mezzio\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via mezzio-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            App\Handler\CheckEmail::class => App\Handler\CheckEmailFactory::class,
            App\Handler\Movies::class => App\Handler\MoviesFactory::class,
            App\Handler\Newsletter::class => App\Handler\NewsletterFactory::class,
            App\Handler\OK::class => App\Handler\OKFactory::class,
            App\Handler\ValidateEmail::class => App\Handler\ValidateEmailFactory::class,
            App\Middleware\CheckPost::class => App\Middleware\CheckPostFactory::class,
        ],
    ],
];
